# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: create private directory for later step
      run: mkdir private
    
    - name: restore signing props to root
      uses: RollyPeres/base64-to-path@v1
      with:
        filePath: ${{ github.workspace }}/sign.props
        encodedString: ${{ secrets.SIGNPROPS }}
        
    - name: restore certificate to private dir
      uses: RollyPeres/base64-to-path@v1
      with:
        filePath: ${{ github.workspace }}/private/reporting.p7b
        encodedString: ${{ secrets.CERTFILE }}
        
    - name: restore keystore to private dir
      uses: RollyPeres/base64-to-path@v1
      with:
        filePath: ${{ github.workspace }}/private/skmeng.jks
        encodedString: ${{ secrets.KEYSTORE }}
        
    - name: permission to build file
      run: chmod a+rwx ./gradlew

    - name: Build with Gradle
      run: ./gradlew buildSignedModule
      
    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: skmSFTP-1.0.0
        path: build/skmSFTP.modl
